version: '3.9'
services:
  mysqldb:
    image: mysql:8.0.23
    env_file:
      - /.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql

  app:
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    restart: on-failure
    ports:
      - "8081:8080"
    build:
      dockerfile: ./Dockerfile
    depends_on:
      - mysqldb

volumes:
  db:
  mysqldb_test: