spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkgames?useSSL=false&serverTimezone=CET
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/kkgames?useSSL=false&serverTimezone=CET
    user: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
    schemas: kkgames
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysqldb:3306/kkgames?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    user: kkgames
    password: kkgames
    url: jdbc:mysql://mysqldb:3306/kkgames?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    schemas: kkgames
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect