spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkgames?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: kkgames
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 7070

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://mysqldb:3306/kkgames?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: kkgames
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: deploy
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: ${database.schema}
    url: ${database.url}
    user: ${database.username}
    password: ${database.password}
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  address: 178.235.178.232