spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkgames?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: kkgames
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://mysqldb:3306/kkgames?useSSL=false&serverTimezone=CET&allowPublicKeyRetrieval=true
    username: kkgames
    password: kkgames123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    schemas: kkgames
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    schemas: ${DB_FLYWAY_SCHEMA}